// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mafasel-homepage/Homepage.tsx": () => import("../components/mockups/mafasel-homepage/Homepage.tsx"),
  "./components/mockups/mafasel-presentation/Presentation.tsx": () => import("../components/mockups/mafasel-presentation/Presentation.tsx")
};
